language: node_js
node_js: node

cache: yarn

before_script:
  - npm install -g yarn
  - yarn

script:
  - yarn test

after_success:
  - yarn coverage

notifications:
  email: false
  slack:
    rooms:
      secure: NEc5gIdX4RMLubMOEvZUPGYSAX4hhtZPSn1h2LM/I/FOxZsXsvaxC5NFwdoJxU6M8c8UTBmud8DUf7Rrt1nTxuqI7ZsaD+TV0nz6OFRSCUH+X0cc94exJpNH0b2fNnHrNqfBXVlFnckeNi5xE+J3h/x6tcFpKO4fC+Q3cLo8bhasZrq/LTa2H7dF0kCrTgsDeD08uEpWVHb26UT0faSqJxu/d5l+O4vSiIVplunEmjvZptWeZNTCKsTnsxjq/hcLad+PQJBqmMTZ84IkDln+JmWOteei8DoCOUoi42eO+9xYD4pCptVZXzqrXDmGj6DCVkApwlisXrNE9P2fiI4Oxf2YmtGRJmtE8ZFZfqlfCwB0SAX91CLvfmPIExJ6+FAcQvI1TCdhCS9v52wRP9XZISCYtMwFce3k7uPo8t//OX39jnokK5PrEivc/cOU/x7nECToDKnMGEb9kmWVFrNYx4HRAEMZ4RodApOCUZYplYmPCnfo4lcvl5sdlvaXvn35YhCHkmOE1mPizXlnqtnNCuJEXoQ2rFfXN6ArkjIhf9su8AjCCGKZon+6oPiZH3E0L5XBy9GA8nL+fVssGZGrWCtCIqDRve10DqZPeaj7NpYueSvzbotivIpOI9HQeQZBXPylAM2iYmaNUuuv6sFanvhAb/4NYErLRF3Ga+QoIDM=
    on_success: change
