language: node_js
node_js: node

cache: yarn

before_script:
  - npm install -g yarn
  - yarn

script:
  - yarn test

notifications:
  email: false
  slack:
    rooms:
      secure: NL74oJ+p+qefnrNxR+N3ukJxEU/T5IWpOJDaWY8cvIZr2v2uN0gCd+1TUZinTy5uj7tZzG/ChUZ0XxwQfmfXdnA18fr91XGy39TGG1KolOZtLUugsfBgEpavgj4UmyygcCtp9ZrSwgmW+3VNIQlIGcLopy1aU5lG22pMo412sVRcgKnZ7k4rO91ugCS0aLPZXW+dC1m2WL8TOK7sxLG8KxnRgOMizSkONBmiMsg2Og8jUZ6rutO18GLCXR2L3pTi3kLJQ++BsweVc4xkEQqmkmRaL6/5Q2U6g0jwq4K0Q+Ts71kNvfnuOfWv/QGZmlT+biQkhAxye9E+0gOZFquL8GlMXKhlRH0NX+uaIl7rjZmlJm2eBM6rXMaCGdN8Ryp1UuWNeVohFW+Ahrt4MCrIS5D2Td+YoH3nnnvVza1udctw/0rf+LIYunM14+UbaBJxqTga4rei0AEZ0SjPXq3+37gPSmbOJ+ycnmWrvsQ9JbKoihVYDN96+3QfoAd45nkQYKgk9bnpKcjH+BfblkXWWFfVENCCV0KMCI4U3evjF2IzNK5E+pu7VrbeYf4VEc2RdTlYPNauNd80SchGKfX2KgH3zUPUJbBehlEXVxEJ6ZQ+n5SxC/eaIZFl+7Hhi5HmRvBKDEx4ivF1ADqmk+uuBmiYN8SR8tCtHnAaSQL8pNc=
    on_success: change
