language: node_js
node_js: node

cache: yarn

before_script:
  - npm install -g yarn
  - yarn

script:
  - yarn lint
  - yarn build
  - yarn test

after_success:
  - yarn coverage

notifications:
  email: false
  slack:
    rooms:
      secure: ORY+b62iQQQf1tPPBKUOW/F9Z6s1FhYgF7D6CPcsQXUs3gRxTyfmdPTK/00tExw3XilAn6BRFLUdT4gpmBg2AKwGYtkp7zVpizKuTxItlXn1s86c8EEmMplKY37PXbkJ7+1HpE9jvXZnUsShX0MxhUTrih9SEklnbScuSCNWhdacvlwK8PzZLtdldGFSCFsPRNBiz7Xf1JrURFwu+bdUdKVOrKm9Zjr5bOiq4mTp1VW5Y9ql/cnHp3f/Ie76A4iM/AJ3W79FisdAiW6ZuHecEOYYqQtWCK0DJhoc1j+rtALL8dVMDdbj78HXdPYTETlys5qfI+GyHUxfj6CQdYxSN4RKil0Tlllm6nKiwatUdr3EQwvaLJYfjn2VZOd+246WzziupoaBa9zxBH5EOJ8YxGxmBWBK7zSnSJJHK80z6OrlhLJDUlxH47YvjAfaG77vClSJ1MIEXR+wBmoCeUfsxVc7TcQnWr9ufy1UvS8BadEe2ymAXVo0wSmACi5v3VIAWbPNhv7DbBsGJTAJRtGLmKh8r60iblW+n98sVPXashewwBVEolGgJ5Jllg/a7lK0G+oGq6e8CVZx7gMptBvYZi8tSle+Hchdp3YjxIO0z5A7JITMGhUbEwNegz2bXujtqz3cMzleja7+hBafEzhAfQ7LMzlhSq4VJnoRR7XsTm4=
    on_success: change
