language: node_js
node_js: node

cache: yarn

before_script:
  - npm install -g yarn
  - yarn

script:
  - yarn test

notifications:
  email: false
  slack:
    rooms:
      secure: ea5x4llYFNTAWqSnl/3C0toksrv/X7RWPMPoo4Pkw3C2oFYaR3OHDANEjA0kfSdyxnHyJX63ca34W6I/hYdACTSpgQli+iQB5Wnytg1gg9v/EvBPJuCRhjba+NfO4avgoXxtW+mX3djs2V3u36D5vQhIFNuL5qoOYXRTtWrUH4RMMPnY/V96l5+N8Ve90zOJhpQ7Hv6UAED9qfcRYRJMwGhi/xQus0HPFbEQDEsp814xKp0rZd5lZ6vaSVtZCEVHX4Qs9nDf5REqO/8D4zsndQoKjWIGcRyWDPWlzEWVYHQ4iHdHWfS502GLvHB7PUp73NH+xzvpBuwu46lePEVFDxR+m/cZ4MoNChha75xbTiSgj/YFsTEAfaIcKGbnYpacxEaj87U7FoTyG+BWnNR+v2WwW4A1lsbJkJVgtA1HhHH3zlnh41oddr1Zs7rYP3jR7X8KsBPSKOcNkPWvzJfWfo97EMjdEat5VGXFG/8FQ4ot8C9rVDCmByu+0ExC8tHfG+84e68wdbJdlNTFqSuyNK3axMfMFQsWP1ETfRSXwGEWmPtnYI/ac3keoRGD21t3/xGqqYlb/5Q5S/WHyyseCM8H2sCKyyXf+Zf4bqTAxhueIb9HaPinUezgMqmIh+Ojg4jIzfKlOsLSD750jtD6yB229thfgf1VVehVZcKSiWE=
    on_success: change
